name: Security Scan
on: [push, pull_request, workflow_dispatch]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mahi7000/Developer_Vulnerability_Scanner@v1.0.3
        with:
          scan-path: './src'
          fail-on-issues: true
